;;; Tests of types and classes
(compile-and-load "ANSI-TESTS:AUX;types-aux.lsp")

(load "types-and-classes/types-and-class.lsp")
(load "types-and-classes/types-and-class-2.lsp")
(load "types-and-classes/coerce.lsp")
(load "types-and-classes/subtypep.lsp")
(load "types-and-classes/subtypep-integer.lsp")
(load "types-and-classes/subtypep-float.lsp")
(load "types-and-classes/subtypep-rational.lsp")
(load "types-and-classes/subtypep-real.lsp")
#-lispworks (load "types-and-classes/subtypep-cons.lsp")
(load "types-and-classes/subtypep-member.lsp")
(load "types-and-classes/subtypep-eql.lsp")
(load "types-and-classes/subtypep-array.lsp")
(load "types-and-classes/subtypep-function.lsp")
(load "types-and-classes/subtypep-complex.lsp")

(load "types-and-classes/deftype.lsp")
(load "types-and-classes/standard-generic-function.lsp")
(load "types-and-classes/type-of.lsp")
(load "types-and-classes/typep.lsp")
(load "types-and-classes/class-precedence-lists.lsp")
