(load "compile-and-load.lsp")
(load "rt/rt-package.lsp")
(compile-and-load "rt/rt.lsp")
;;; (unless (probe-file "rt/rt.o") (compile-file "rt/rt.lsp"))
;;; (load "rt/rt.o")
(load "cl-test-package.lsp")
(in-package :cl-test)
(compile-and-load "aux.lsp")
;;; (unless (probe-file "aux.o") (compile-file "aux.lsp"))
;;; (load "aux.o")
(load "universe.lsp")
