;;; Tests of conses

(load "cons-test-01.lsp")
(load "cons-test-02.lsp")
(load "cons-test-03.lsp")
(load "cons-test-04.lsp")
(load "cons-test-05.lsp")
(load "cons-test-06.lsp")
(load "cons-test-07.lsp")
(load "cons-test-08.lsp")
(load "cons-test-09.lsp")
(load "cons-test-10.lsp")
(load "cons-test-11.lsp")
(load "cons-test-12.lsp")
(load "cons-test-13.lsp")
(load "cons-test-14.lsp")
(load "cons-test-15.lsp")
(load "cons-test-16.lsp")
(load "cons-test-17.lsp")
(load "cons-test-18.lsp")
(load "cons-test-19.lsp")
(load "cons-test-20.lsp")
(load "cons-test-21.lsp")
(load "cons-test-22.lsp")
(load "cons-test-23.lsp")
(load "cons-test-24.lsp")
(load "cons-test-25.lsp")
